<?php

namespace ContainerKZBbd7Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CfZXh5mService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.CfZXh5m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CfZXh5m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sensorDetail' => ['privates', '.errored..service_locator.CfZXh5m.App\\Entity\\SensorDetail', NULL, 'Cannot autowire service ".service_locator.CfZXh5m": it references class "App\\Entity\\SensorDetail" but no such service exists.'],
        ], [
            'sensorDetail' => 'App\\Entity\\SensorDetail',
        ]);
    }
}
