<?php

namespace ContainerQsuB8DC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0NlsQzpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0NlsQzp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0NlsQzp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sensorAlert' => ['privates', '.errored..service_locator.0NlsQzp.App\\Entity\\SensorAlerts', NULL, 'Cannot autowire service ".service_locator.0NlsQzp": it references class "App\\Entity\\SensorAlerts" but no such service exists.'],
        ], [
            'sensorAlert' => 'App\\Entity\\SensorAlerts',
        ]);
    }
}
