<?php

namespace ContainerQsuB8DC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensorDetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CfZXh5m.App\Entity\SensorDetail' shared service.
     *
     * @return \App\Entity\SensorDetail
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CfZXh5m": it references class "App\\Entity\\SensorDetail" but no such service exists.');
    }
}
