<?php

namespace ContainerQsuB8DC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensorAlertsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0NlsQzp.App\Entity\SensorAlerts' shared service.
     *
     * @return \App\Entity\SensorAlerts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0NlsQzp": it references class "App\\Entity\\SensorAlerts" but no such service exists.');
    }
}
