<?php

namespace ContainerAD2ltkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QQdmvwGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QQdmvwG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QQdmvwG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\SensorAlertsController::delete' => ['privates', '.service_locator.0NlsQzp', 'get_ServiceLocator_0NlsQzpService', true],
            'App\\Controller\\SensorAlertsController::edit' => ['privates', '.service_locator.0NlsQzp', 'get_ServiceLocator_0NlsQzpService', true],
            'App\\Controller\\SensorAlertsController::index' => ['privates', '.service_locator.NtcALKc', 'get_ServiceLocator_NtcALKcService', true],
            'App\\Controller\\SensorAlertsController::show' => ['privates', '.service_locator.0NlsQzp', 'get_ServiceLocator_0NlsQzpService', true],
            'App\\Controller\\SensorDetailController::delete' => ['privates', '.service_locator.CfZXh5m', 'get_ServiceLocator_CfZXh5mService', true],
            'App\\Controller\\SensorDetailController::edit' => ['privates', '.service_locator.CfZXh5m', 'get_ServiceLocator_CfZXh5mService', true],
            'App\\Controller\\SensorDetailController::index' => ['privates', '.service_locator.jjPJBEc', 'get_ServiceLocator_JjPJBEcService', true],
            'App\\Controller\\SensorDetailController::show' => ['privates', '.service_locator.CfZXh5m', 'get_ServiceLocator_CfZXh5mService', true],
            'App\\Controller\\SensorMeasurementController::add_sensor_measurement' => ['privates', '.service_locator.jjPJBEc', 'get_ServiceLocator_JjPJBEcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\SensorAlertsController:delete' => ['privates', '.service_locator.0NlsQzp', 'get_ServiceLocator_0NlsQzpService', true],
            'App\\Controller\\SensorAlertsController:edit' => ['privates', '.service_locator.0NlsQzp', 'get_ServiceLocator_0NlsQzpService', true],
            'App\\Controller\\SensorAlertsController:index' => ['privates', '.service_locator.NtcALKc', 'get_ServiceLocator_NtcALKcService', true],
            'App\\Controller\\SensorAlertsController:show' => ['privates', '.service_locator.0NlsQzp', 'get_ServiceLocator_0NlsQzpService', true],
            'App\\Controller\\SensorDetailController:delete' => ['privates', '.service_locator.CfZXh5m', 'get_ServiceLocator_CfZXh5mService', true],
            'App\\Controller\\SensorDetailController:edit' => ['privates', '.service_locator.CfZXh5m', 'get_ServiceLocator_CfZXh5mService', true],
            'App\\Controller\\SensorDetailController:index' => ['privates', '.service_locator.jjPJBEc', 'get_ServiceLocator_JjPJBEcService', true],
            'App\\Controller\\SensorDetailController:show' => ['privates', '.service_locator.CfZXh5m', 'get_ServiceLocator_CfZXh5mService', true],
            'App\\Controller\\SensorMeasurementController:add_sensor_measurement' => ['privates', '.service_locator.jjPJBEc', 'get_ServiceLocator_JjPJBEcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\SensorAlertsController::delete' => '?',
            'App\\Controller\\SensorAlertsController::edit' => '?',
            'App\\Controller\\SensorAlertsController::index' => '?',
            'App\\Controller\\SensorAlertsController::show' => '?',
            'App\\Controller\\SensorDetailController::delete' => '?',
            'App\\Controller\\SensorDetailController::edit' => '?',
            'App\\Controller\\SensorDetailController::index' => '?',
            'App\\Controller\\SensorDetailController::show' => '?',
            'App\\Controller\\SensorMeasurementController::add_sensor_measurement' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\SensorAlertsController:delete' => '?',
            'App\\Controller\\SensorAlertsController:edit' => '?',
            'App\\Controller\\SensorAlertsController:index' => '?',
            'App\\Controller\\SensorAlertsController:show' => '?',
            'App\\Controller\\SensorDetailController:delete' => '?',
            'App\\Controller\\SensorDetailController:edit' => '?',
            'App\\Controller\\SensorDetailController:index' => '?',
            'App\\Controller\\SensorDetailController:show' => '?',
            'App\\Controller\\SensorMeasurementController:add_sensor_measurement' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
