<?php

namespace ContainerROWSiyP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPostRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\BlogPostRepository' shared autowired service.
     *
     * @return \App\Repository\BlogPostRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BlogPostRepository'] = new \App\Repository\BlogPostRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
