<?php

namespace ContainerROWSiyP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHelloWorldControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\HelloWorldController' shared autowired service.
     *
     * @return \App\Controller\HelloWorldController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\HelloWorldController'] = new \App\Controller\HelloWorldController();
    }
}
