<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0YaAbUU\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0YaAbUU/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container0YaAbUU.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container0YaAbUU\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container0YaAbUU\App_KernelTestDebugContainer([
    'container.build_hash' => '0YaAbUU',
    'container.build_id' => '5a5ae65a',
    'container.build_time' => 1608131435,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0YaAbUU');
