<?php

namespace Container0YaAbUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NtcALKcService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.NtcALKc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NtcALKc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sensorAlertsRepository' => ['privates', 'App\\Repository\\SensorAlertsRepository', 'getSensorAlertsRepositoryService', true],
        ], [
            'sensorAlertsRepository' => 'App\\Repository\\SensorAlertsRepository',
        ]);
    }
}
